### ISSUE TITLE
Code scanning alerts reveal secrets

### ISSUE THREAD

**Issue by the-tatanka** [DariuszPorowski/github-action-gitleaks#38]
Unfortunately the findings in the code scanning alerts contain the secrets themselves - is that intentional?
Example: https://github.com/the-tatanka/github-action-gitleaks/security/code-scanning

![image](https://user-images.githubusercontent.com/59142915/160706640-34bdd3d3-ef22-4792-9dd8-7940de3327b3.png)

Would be good for security reasons that the secrets would not be shown here too.

Maybe a "redact" flag would be good here as well.

Great action, also good that the Azure secrets are included.

**Comment by DariuszPorowski** [comment]
Hello @the-tatanka I do not have access to provied repo for investigating the issue.
redact is enabled by default, but it only works for geitleaks output log.

**Comment by the-tatanka** [comment]
ok, thnaks for the answer and the action.
Redact option for gitleaks output works as aspected.
Looks like GitHub displays the matching code snippet.
