### ISSUE TITLE
Bug regression -- invalid git revision traversal

### ISSUE THREAD

**Issue by lawndoc** [DariuszPorowski/github-action-gitleaks#66]
Hey @DariuszPorowski, it looks like [this line](https://github.com/DariuszPorowski/github-action-gitleaks/blob/4410bd5353adccb508100a3d1660aee9c93289fa/entrypoint.sh#L80) regressed in [this commit](https://github.com/DariuszPorowski/github-action-gitleaks/commit/4410bd5353adccb508100a3d1660aee9c93289fa) and brought back a [bug](https://github.com/DariuszPorowski/github-action-gitleaks/issues/58) that was dealt with in #62.

We are seeing the action fail again in some situations when the first commit reference doesn't exist (due to the `^` reference).

![github_error](https://github.com/DariuszPorowski/github-action-gitleaks/assets/24688343/8bc97a1b-3137-4cf9-bbc7-c251cd592b7c)

Was reverting from `...` back to `^..` directly related to the fix for #64? It's hard to tell because there were lots of changes in the regression commit and I wasn't involved in that one.

**Comment by DariuszPorowski** [comment]
@lawndoc oh shoot, my bad - do not why restored it.
